<a href="https://colab.research.google.com/github/phaneo/TF2-Complete/blob/main/00_Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# To cover the most fundamental concepts of tensors using Tensorflow.

* Intro to tensors
* Getting info from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function
* Using GPU's for TF
* Exercises

## Intro to tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


### Creating tensors with tf.constant()

In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the no. of dimensions of a tensor
scalar.ndim

0

In [ ]:
# Create a vector
vect = tf.constant([10, 10])
vect

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Create a matrix
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 5.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  5.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                      [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### Creating a tensor with `tf.Variable()`

In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

In [ ]:
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(6)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([6, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(6)
unchangeable_tensor

AttributeError: ignored

### Creating random tensors

In [ ]:
random_tensor_1 = tf.random.Generator.from_seed(42)
random_tensor_1 = random_tensor_1.normal(shape=(3, 2))
random_tensor_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_tensor_2 = tf.random.Generator.from_seed(42)
random_tensor_2 = random_tensor_2.normal(shape=(3, 2))
random_tensor_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_tensor_1 == random_tensor_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in a tensor

In [ ]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4,],
                            [2, 5]])
not_shuffled.ndim

2

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Creating tensors from numpy arrays

In [ ]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
X = tf.constant(numpy_A)
X

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
Y = tf.constant(numpy_A, shape=(3, 8))
Y

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

## Getting information from tensors

When dealing with tensors, we would need to be aware of the following attributes:
* Shape
* Rank
* Dimension
* Size

In [ ]:
# Create a rank 4 tensor (4-dimensions)

rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
# Get various attributes of our tensor

print("Datatype of every element of the tensor: ", rank_4_tensor.dtype)
print("No. of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of the tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total no. of elements in our tensor: ", tf.size(rank_4_tensor).numpy())


Datatype of every element of the tensor:  <dtype: 'float32'>
No. of dimensions (rank):  4
Shape of the tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total no. of elements in our tensor:  120


### Indexing tensors

In [ ]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension except for the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2-dimension)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
rank_2_tensor.shape

TensorShape([2, 2])

In [ ]:
rank_2_tensor.ndim

2

In [ ]:
rank_2_tensor[:, -1].numpy()

array([7, 4], dtype=int32)

In [ ]:
# Add extra dimension to the rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
# Expand the 1st axis
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

# Manipulating tensors (tensor operations)

`+`, `-`, `*`, `/`

In [ ]:
# We can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [ ]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

# Matrix multiplication

In [ ]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Create a tensor of (3, 2) shape
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
X @ Y

InvalidArgumentError: ignored

In [ ]:
tf.matmul(X, Y)

InvalidArgumentError: ignored

In [ ]:
# Let's change the shape of Y
Y, tf.reshape(Y, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [ ]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# Can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape = (2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

## Changing the datatype of a tensor

In [ ]:
# Create a tensor with default dtype (float32)
B = tf.constant([1.7, 3.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 3.4], dtype=float32)>,
 tf.float32)

In [ ]:
C = tf.constant([3, 10])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 3.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E= tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 3., 10.], dtype=float32)>,
 tf.float32)

In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16, E_float16.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 3., 10.], dtype=float16)>,
 tf.float16)

## Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amt of values.

In [ ]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Absolute value of a tensor
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's get through the following:
* Minimum of a tensor
* Maximum of a tensor
* Mean of a tensor
* Sum of a tensor

In [ ]:
# Create a large tensor
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([87, 15, 78, 88, 13, 64, 18, 97, 71, 22, 45, 54, 62, 81, 96, 19, 53,
       48, 90, 10, 33, 42, 31, 30, 23, 77, 69, 84, 43, 89, 18,  2, 42,  2,
       61, 43, 44, 64,  5, 49, 84, 25, 96, 34, 55, 58, 29, 30, 32, 55])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2460>

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.37298>

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=749.28>

In [ ]:
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [ ]:
tf.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=31>

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Squeezing a tensor (removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=[1, 1, 1, 1, 50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

## Exercises

In [ ]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

vector = tf.constant([1, 5])
scalar = tf.constant(18)
matrix = tf.constant([[10, 8],
                      [9, 9],
                      [2, 16]])
tensor = tf.constant([[[1, 2],
                       [3, 4]],
                      [[5, 6],
                      [7, 8]],
                      [[9, 10],
                       [11, 12]]])
print("Vector: ", vector)
print("Scalar: ", scalar)
print("Matrix: ", matrix)
print("Tensor: ", tensor)

Vector:  tf.Tensor([1 5], shape=(2,), dtype=int32)
Scalar:  tf.Tensor(18, shape=(), dtype=int32)
Matrix:  tf.Tensor(
[[10  8]
 [ 9  9]
 [ 2 16]], shape=(3, 2), dtype=int32)
Tensor:  tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(3, 2, 2), dtype=int32)


In [ ]:
tensor.shape, tensor.ndim, tf.size(tensor).numpy()

(TensorShape([3, 2, 2]), 3, 12)

In [ ]:
tensor_1 = tf.constant(tf.random.uniform(shape=[5, 300]))
tensor_2 = tf.constant(tf.random.uniform(shape=[5, 300]))
tensor_1, tensor_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.84848344, 0.6335293 , 0.71483827, ..., 0.5210159 , 0.6620507 ,
         0.7164959 ],
        [0.46931076, 0.88998175, 0.99655545, ..., 0.71958125, 0.25405073,
         0.32736707],
        [0.17905343, 0.01055408, 0.36842656, ..., 0.88817155, 0.35124195,
         0.05358148],
        [0.48750746, 0.3640989 , 0.87152207, ..., 0.55370355, 0.26883352,
         0.98255324],
        [0.40583944, 0.85986674, 0.15569866, ..., 0.83371186, 0.43026888,
         0.6543292 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.34640205, 0.7737855 , 0.10414386, ..., 0.7190157 , 0.38322234,
         0.36399138],
        [0.3719101 , 0.29858088, 0.3467387 , ..., 0.32596362, 0.9827858 ,
         0.02345216],
        [0.46845984, 0.5418314 , 0.6870177 , ..., 0.81563663, 0.8927487 ,
         0.11154389],
        [0.66827404, 0.07904243, 0.1129477 , ..., 0.05235088, 0.25467575,
         0.508906  ],
        [0.09607

In [ ]:
tf.matmul(tensor_1, tf.reshape(tensor_2, shape=(300, 5)))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.0412  , 76.95565 , 77.688995, 82.79054 , 82.58045 ],
       [76.27828 , 78.72277 , 73.26598 , 80.29095 , 79.65198 ],
       [77.06555 , 78.34927 , 76.75403 , 82.45426 , 81.725845],
       [80.42058 , 79.80696 , 78.401855, 82.89572 , 78.789055],
       [77.82882 , 76.78781 , 73.81938 , 80.86696 , 77.15143 ]],
      dtype=float32)>

In [ ]:
tf.multiply(tensor_1, tensor_2)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.2939164 , 0.49021578, 0.07444602, ..., 0.37461862, 0.25371262,
        0.26079834],
       [0.17454141, 0.26573154, 0.34554434, ..., 0.2345573 , 0.24967745,
        0.00767747],
       [0.08387934, 0.00571853, 0.25311556, ..., 0.72442526, 0.3135708 ,
        0.00597669],
       [0.3257886 , 0.02877926, 0.09843642, ..., 0.02898687, 0.06846537,
        0.50002724],
       [0.03899119, 0.78209144, 0.09827036, ..., 0.48917767, 0.22031468,
        0.5385405 ]], dtype=float32)>

In [ ]:
tensor_3 = tf.constant(tf.random.uniform(shape=[224, 224, 3]))
tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.26363337, 0.57727563, 0.72897387],
        [0.14994097, 0.6941651 , 0.6123247 ],
        [0.68104327, 0.575696  , 0.9579706 ],
        ...,
        [0.0103147 , 0.8148682 , 0.98014927],
        [0.20876467, 0.39117444, 0.70476186],
        [0.6356151 , 0.87263644, 0.60124314]],

       [[0.6769953 , 0.37963772, 0.5406096 ],
        [0.08968794, 0.16773939, 0.6639664 ],
        [0.44339693, 0.24464595, 0.11879373],
        ...,
        [0.02649748, 0.6395147 , 0.8629186 ],
        [0.44135797, 0.09503901, 0.66869795],
        [0.04473794, 0.7845745 , 0.58462036]],

       [[0.73907185, 0.49122536, 0.07879961],
        [0.1969099 , 0.03860652, 0.9528905 ],
        [0.01551056, 0.86056054, 0.13418686],
        ...,
        [0.63694465, 0.73656905, 0.07782304],
        [0.01225758, 0.3423425 , 0.22882223],
        [0.5925195 , 0.9396126 , 0.6641723 ]],

       ...,

       [[0.79004323, 0.04542744, 0.11651707],
        [0.53

In [ ]:
tf.reduce_max(tensor_3, axis=0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.9997517 , 0.9993019 , 0.9983636 ],
       [0.99836016, 0.9918145 , 0.9882662 ],
       [0.987296  , 0.99771404, 0.99599445],
       [0.99992764, 0.99908423, 0.99193573],
       [0.9941894 , 0.9982852 , 0.99979496],
       [0.99945736, 0.988158  , 0.99780047],
       [0.997149  , 0.99017584, 0.99087536],
       [0.9979726 , 0.9920391 , 0.99310255],
       [0.99880016, 0.99827754, 0.9991994 ],
       [0.9935055 , 0.9978858 , 0.99764085],
       [0.9996346 , 0.9978875 , 0.9986973 ],
       [0.992506  , 0.999161  , 0.9968817 ],
       [0.997     , 0.9994688 , 0.9934436 ],
       [0.9995849 , 0.99989057, 0.9997457 ],
       [0.99838567, 0.99843657, 0.9930192 ],
       [0.9944906 , 0.9972098 , 0.9991101 ],
       [0.990996  , 0.98954177, 0.99827635],
       [0.9963982 , 0.99852943, 0.99961984],
       [0.99459875, 0.9986067 , 0.9962691 ],
       [0.9993005 , 0.99360204, 0.990553  ],
       [0.98553205, 0.9974505 , 0.9955386 ],
     

In [ ]:
tf.reduce_min(tensor_3, axis=0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[4.32848930e-04, 1.07411146e-02, 9.41395760e-04],
       [1.57022476e-03, 1.07789040e-03, 1.10890865e-02],
       [3.93569469e-03, 2.99513340e-03, 2.76160240e-03],
       [2.21216679e-03, 8.96906853e-03, 7.61783123e-03],
       [6.42573833e-03, 9.77802277e-03, 9.32526588e-03],
       [1.25271082e-02, 2.11424828e-02, 2.44212151e-03],
       [1.15076303e-02, 6.28471375e-04, 9.67502594e-04],
       [2.70259380e-03, 6.72292709e-03, 9.66501236e-03],
       [1.28431320e-02, 2.76911259e-03, 7.10093975e-03],
       [2.13479996e-03, 3.93545628e-03, 1.65629387e-03],
       [1.37008429e-02, 3.14402580e-03, 4.96268272e-04],
       [1.30629539e-03, 2.61116028e-03, 1.81615353e-03],
       [1.74987316e-03, 1.56267881e-02, 4.63116169e-03],
       [4.43816185e-04, 1.83373690e-02, 6.25109673e-03],
       [1.62959099e-04, 1.29830837e-03, 1.79195404e-03],
       [1.76846981e-03, 4.37211990e-03, 3.83853912e-05],
       [1.50051117e-02, 2.11393833e-03

In [ ]:
tensor_4 = tf.constant(tf.random.normal(shape=[1, 224, 224, 3]))
tensor_4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[ 1.45628619e+00, -1.24749683e-01,  1.49693787e+00],
         [-4.06756371e-01, -1.20192252e-01, -1.27209187e+00],
         [ 1.09631121e+00,  2.59195656e-01,  1.98842511e-01],
         ...,
         [-3.70970875e-01,  1.07680237e+00,  6.21225834e-01],
         [-1.11593544e+00,  3.89632545e-02,  5.63541651e-01],
         [ 1.18949011e-01,  1.16331303e+00,  3.70487547e-03]],

        [[ 5.53124130e-01, -8.57210696e-01,  1.20315945e+00],
         [-1.26289535e+00, -4.22253609e-01, -1.34504855e+00],
         [ 2.73386478e-01, -1.20167565e+00,  1.38267141e-03],
         ...,
         [-1.87881994e+00,  1.89147973e+00,  7.02602386e-01],
         [ 5.87118864e-01,  1.31602490e+00, -1.49335194e+00],
         [-6.81881845e-01, -1.68258274e+00,  1.26258576e+00]],

        [[ 1.37159348e+00, -5.20022549e-02, -4.02174473e-01],
         [ 1.48849201e+00, -1.00744224e+00,  1.21387744e+00],
         [ 1.81927264e-01,  8.68243635e-01

In [ ]:
tf.squeeze(tensor_4)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ 1.45628619e+00, -1.24749683e-01,  1.49693787e+00],
        [-4.06756371e-01, -1.20192252e-01, -1.27209187e+00],
        [ 1.09631121e+00,  2.59195656e-01,  1.98842511e-01],
        ...,
        [-3.70970875e-01,  1.07680237e+00,  6.21225834e-01],
        [-1.11593544e+00,  3.89632545e-02,  5.63541651e-01],
        [ 1.18949011e-01,  1.16331303e+00,  3.70487547e-03]],

       [[ 5.53124130e-01, -8.57210696e-01,  1.20315945e+00],
        [-1.26289535e+00, -4.22253609e-01, -1.34504855e+00],
        [ 2.73386478e-01, -1.20167565e+00,  1.38267141e-03],
        ...,
        [-1.87881994e+00,  1.89147973e+00,  7.02602386e-01],
        [ 5.87118864e-01,  1.31602490e+00, -1.49335194e+00],
        [-6.81881845e-01, -1.68258274e+00,  1.26258576e+00]],

       [[ 1.37159348e+00, -5.20022549e-02, -4.02174473e-01],
        [ 1.48849201e+00, -1.00744224e+00,  1.21387744e+00],
        [ 1.81927264e-01,  8.68243635e-01, -1.50823951e-01],


In [ ]:
tensor_5 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tensor_5

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [ ]:
tf.argmax(tensor_5).numpy()

9

In [ ]:
tf.one_hot(tensor_5, depth=11, dtype=tf.int32)

<tf.Tensor: shape=(10, 11), dtype=int32, numpy=
array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)>